
name: deploy
on:
  create:
    tags:
    - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set azure kubectl context
      uses: azure/aks-set-context@v1
      with:
          creds: '${{ secrets.AKS_CREDENTIALS }}'
          resource-group: workgroup
          cluster-name: workback
      id: login
    - name: production deployment
      shell: bash
      env:
        METALBACK_CONFIG: '${{ secrets.METALBACK_CONFIG }}'
        AUTH_SERVER_PUBLIC_PEM: '${{ secrets.AUTH_SERVER_PUBLIC_PEM }}'
        AUTH_SERVER_PRIVATE_PEM: '${{ secrets.AUTH_SERVER_PRIVATE_PEM }}'
      run: |
        cd metalback
        rm -rf config && mkdir config
        echo "$METALBACK_CONFIG" > config/config.yaml
        echo "$AUTH_SERVER_PUBLIC_PEM" > config/auth-server.public.pem
        echo "$AUTH_SERVER_PRIVATE_PEM" > config/auth-server.private.pem
        ./proddeploy
